function captureCurrentDiv()
{
    html2canvas([document.getElementById('main-container')], {   
        onrendered: function(canvas)  
        {
            var img = canvas.toDataURL()
            $.post("save.php", {data: img}, function (file) {
            window.location.href =  "download.php?path="+ file});   
        }
    });
}
	
function captureFullPage()
	{
		html2canvas(document.body, {  
			onrendered: function(canvas)  
			{
				var img = canvas.toDataURL()
				$.post("save.php", {data: img}, function (file) {
				window.location.href =  "download.php?path="+ file});   
			}
		});
	}



$("#btn").click(function(){

	var myArray = [
		"Try pairing",
		"Give this a shot: pair",
		"Use",
		"Pro tip: pair",
		"Don't forget to pair",
		"Designers: pair",
		"Students: pair",
		"In a rut? Pair",
		"Merge the forces of",
		"Trust me on this one. Pair",
		"Combine the powers of",
		"Try uniting",
		"Try combining",
		"Couple",
		"Link up",
		"Join",
		"You can pair",
		"Next time, pair"
	];

	var randomItem = myArray[Math.floor(Math.random()*myArray.length)];


	var myArray2 = [
		"for",
		"so your work has",
		"to avoid",
		"to construct",
		"to craft",
		"to create",
		"to deliver",
		"to effuse",
		"to emit",
		"to ensure",
		"to establish",
		"to exude",
		"to fake",
		"to generate",
		"to give off",
		"to guarantee",
		"to manufacture",
		"to present",
		"to radiate",
		"to spread"
	];

	var randomItem2 = myArray2[Math.floor(Math.random()*myArray2.length)];


	var myArray3 = [
		"a bold",
		"a bright",
		"a brilliant",
		"a catchy",
		"a clashing",
		"a clear",
		"a compatible",
		"a complementary",
		"a conceptual",
		"a confused",
		"a considered",
		"a contrasting",
		"a controversial",
		"a cool",
		"a curvaceous",
		"a deep",
		"a déjà vu",
		"a delicate",
		"a depressing",
		"a discordant",
		"a distinctive",
		"a dramatic",
		"a familiar",
		"a flowing",
		"a garish",
		"a gaudy",
		"a harmonious",
		"a harmonious",
		"a jarring",
		"a lasting",
		"a lively",
		"a mainstream",
		"a meaningful",
		"a mellow",
		"a memorable",
		"a momentous",
		"a muted",
		"a natural",
		"a quiet",
		"a random",
		"a rich",
		"a rustic",
		"a saturated",
		"a soothing",
		"a stimulating",
		"a subdued",
		"a subtle",
		"a swirling",
		"a thought-out",
		"a vibrant",
		"a vintage",
		"a violent",
		"a vivd",
		"a warm",
		"a worn",
		"an angular",
		"an artificial",
		"an earthy",
		"an eduring",
		"an insanely boring",
		"an intense",
		"an intimate",
		"an old-timey",
		"an ordinary",
		"an organic",
		"an unconsidered",
		"an uneven",
		"an unforgettable",
		"an unfriendly",
		"that je ne sais quoi",
		"a stupid",
		"an idiotic",
		"a shitty",
		"a crappy",
		"a foolish",
		"a dumb",
		"a genius",
		"an irresistable",
		"a mind-blowing",
		"an earth-shattering",
		"a questionable",
		"a miserable",
		"a substandard",
		"an inferior",
		"a superior",
		"a downright ugly",
		"a downright sexy",
		"a super special",
		"a fame-destined",
		"a passionate",
		"a hideous",
		"a gnarly",
		"a flirty",
		"a flirtatious",
		"a buttery",
		"an OG",
		"an X-rated",
		"a multidisciplinary",
		"a dimwitted",
		"a delicious",
		"a happy-go-lucky",
		"a fun yet dependable",
		"a bring-home-to-your-mama",
		"a well-groomed",
		"a false yet believable",
		"a raw",
		"a non-conformist",
		"a velvety",
		"a feminine",
		"a masculine",
		"a politically correct",
		"a flamboyant",
		"a cocky",
		"a painfully mainstream",
		"an uber conformist",
		"a heartbreaking",
		"a courteous",
		"a highfalutin",
		"a truly transformative",
		"a temporal",
		"a postmodern",
		"a post postmodern",
		"a frantic and repetitive",
		"a diabolical",
		"an ungodly",
		"a nippy",
		"a high-contrast",
		"a perpetually doomed",
		"a cagey",
		"an easy-to-miss",
		"a progressive",
		"a liberal",
		"a conservative",
		"a new wave",
		"a state-of-the-art",
		"a cutting-edge",
		"a vanguard",
		"a hip",
		"an ultamodern",
		"a kinky",
		"a palsy-walsy",
		"a red-carpet",
		"a refurbished",
		"a wannabe hipster",
		"a gentrified"
	];

	var randomItem3 = myArray3[Math.floor(Math.random()*myArray3.length)];


	var myArray4 = [
		"affectation.",
		"appearance.",
		"aura.",
		"demeanor.",
		"effect.",
		"emotion.",
		"experience.",
		"feel.",
		"feeling.",
		"flavor.",
		"glow.",
		"impression.",
		"je ne sais quoi.",
		"look.",
		"mood.",
		"pattern.",
		"presence.",
		"property.",
		"quality.",
		"semblance.",
		"sensation.",
		"sense of drama.",
		"sensibility.",
		"tone.",
		"undercurrent.",
		"vibe.",
		"concept.",
		"visual language.",
		"sense of style.",
		"voice.",
		"sense of passion.",
		"shitstorm.",
		"spirit.",
		"character.",
		"ambiance.",
		"complexity.",
		"brand experience.",
		"hegemony of distress.",
		"critique of modern day society.",
		"theme.",
		"message.",
		"nuance.",
		"tinge.",
		"connotation."


	];

	var randomItem4 = myArray4[Math.floor(Math.random()*myArray4.length)];



	var myArray5 = [
		"<img src=images/abril-text.png>",
		"<img src=images/adelle.png>",
		"<img src=images/adobe-caslon.png>",
		"<img src=images/agipo.png>",
		"<img src=images/aino.png>",
		"<img src=images/akkurat.png>",
		"<img src=images/aktiv-grotesk.png>",
		"<img src=images/akzidenz-grotesk.png>",
		"<img src=images/albertus.png>",
		"<img src=images/alright-sans.png>",
		"<img src=images/alternate-gothic.png>",
		"<img src=images/anderson-grotesk.png>",
		"<img src=images/anostencil.png>",
		"<img src=images/antenna.png>",
		"<img src=images/antique-olive.png>",
		"<img src=images/archer.png>",
		"<img src=images/arial.png>",
		"<img src=images/asul.png>",
		"<img src=images/atlas-grotesk.png>",
		"<img src=images/avenir-next.png>",
		"<img src=images/avenir.png>",
		"<img src=images/balboa.png>",
		"<img src=images/balloon.png>",
		"<img src=images/barracuda-script.png>",
		"<img src=images/baskerville.png>",
		"<img src=images/bello.png>",
		"<img src=images/belwe.png>",
		"<img src=images/benton-sans.png>",
		"<img src=images/big-caslon.png>",
		"<img src=images/big-noodle-titling.png>",
		"<img src=images/block.png>",
		"<img src=images/bodoni.png>",
		"<img src=images/bookman.png>",
		"<img src=images/brandon-grotesque.png>",
		"<img src=images/breite-fette-information.png>",
		"<img src=images/brevier.png>",
		"<img src=images/broadway.png>",
		"<img src=images/brothers.png>",
		"<img src=images/brush-script.png>",
		"<img src=images/brutal-type.png>",
		"<img src=images/bureau-grot.png>",
		"<img src=images/calibre.png>",
		"<img src=images/canela.png>",
		"<img src=images/century-expanded.png>",
		"<img src=images/century-schoolbook.png>",
		"<img src=images/cheltenham.png>",
		"<img src=images/clarendon.png>",
		"<img src=images/coco.png>",
		"<img src=images/cogito.png>",
		"<img src=images/comic-sans.png>",
		"<img src=images/compacta.png>",
		"<img src=images/contact-atf.png>",
		"<img src=images/conto.png>",
		"<img src=images/cooper-black.png>",
		"<img src=images/copperplate-gothic.png>",
		"<img src=images/corvinus.png>",
		"<img src=images/cosimo.png>",
		"<img src=images/curlz.png>",
		"<img src=images/dala-floda.png>",
		"<img src=images/davida.png>",
		"<img src=images/delphin.png>",
		"<img src=images/dic-sans.png>",
		"<img src=images/digestive.png>",
		"<img src=images/documan.png>",
		"<img src=images/dolly.png>",
		"<img src=images/dover-serif-text.png>",
		"<img src=images/druk-text-wide.png>",
		"<img src=images/eckmannpsych.png>",
		"<img src=images/elephant-alias.png>",
		"<img src=images/euclid-flex.png>",
		"<img src=images/eurostile.png>",
		"<img src=images/fakt.png>",
		"<img src=images/favorit.png>",
		"<img src=images/fb-titling-gothic.png>",
		"<img src=images/fedra-sans.png>",
		"<img src=images/ff-din.png>",
		"<img src=images/ff-fago.png>",
		"<img src=images/ff-mark.png>",
		"<img src=images/ff-meta.png>",
		"<img src=images/folio.png>",
		"<img src=images/founders-grotesk.png>",
		"<img src=images/frankfurter.png>",
		"<img src=images/franklin-gothic.png>",
		"<img src=images/freight-sans.png>",
		"<img src=images/frutiger.png>",
		"<img src=images/futura.png>",
		"<img src=images/futura-black.png>",
		"<img src=images/futura-condensed.png>",
		"<img src=images/futura-display.png>",
		"<img src=images/garage-gothic.png>",
		"<img src=images/gemeli-mono.png>",
		"<img src=images/geogrotesque.png>",
		"<img src=images/georgia.png>",
		"<img src=images/gill-kayo.png>",
		"<img src=images/gill-sans.png>",
		"<img src=images/gotham.png>",
		"<img src=images/goudy-old-style.png>",
		"<img src=images/granjon.png>",
		"<img src=images/graphik.png>",
		"<img src=images/gt-america.png>",
		"<img src=images/gt-pressura-mono.png>",
		"<img src=images/gt-sectra.png>",
		"<img src=images/gt-walsheim.png>",
		"<img src=images/hammer.png>",
		"<img src=images/harbour.png>",
		"<img src=images/helvetica-condensed.png>",
		"<img src=images/helvetica.png>",
		"<img src=images/hobo.png>",
		"<img src=images/hollie-script.png>",
		"<img src=images/house-script.png>",
		"<img src=images/house-slant.png>",
		"<img src=images/icone.png>",
		"<img src=images/infini.png>",
		"<img src=images/interstate.png>",
		"<img src=images/italian-black-ornamented.png>",
		"<img src=images/itc-mendoza.png>",
		"<img src=images/itc-souvenir.png>",
		"<img src=images/jaakko.png>",
		"<img src=images/jaf-domus.png>",
		"<img src=images/kabel-black.png>",
		"<img src=images/kabel.png>",
		"<img src=images/karmina-sans.png>",
		"<img src=images/knif-mono.png>",
		"<img src=images/knockout.png>",
		"<img src=images/krul.png>",
		"<img src=images/kurversbrug.png>",
		"<img src=images/kuzanyan.png>",
		"<img src=images/larish-neue.png>",
		"<img src=images/latin-wide.png>",
		"<img src=images/lato.png>",
		"<img src=images/le-griffe.png>",
		"<img src=images/letrista-script.png>",
		"<img src=images/ll-brown.png>",
		"<img src=images/ll-circular.png>",
		"<img src=images/lydian.png>",
		"<img src=images/lyon.png>",
		"<img src=images/maax.png>",
		"<img src=images/maison-neue.png>",
		"<img src=images/marvin.png>",
		"<img src=images/matter.png>",
		"<img src=images/mensch.png>",
		"<img src=images/mercury.png>",
		"<img src=images/miller.png>",
		"<img src=images/minerale.png>",
		"<img src=images/minion.png>",
		"<img src=images/minotaur-sans.png>",
		"<img src=images/minuscule.png>",
		"<img src=images/mistral.png>",
		"<img src=images/monotype-grotesque.png>",
		"<img src=images/morion.png>",
		"<img src=images/mrs-eaves.png>",
		"<img src=images/museo-sans.png>",
		"<img src=images/neue-haas-grotesk.png>",
		"<img src=images/neue-helvetica.png>",
		"<img src=images/neutraface.png>",
		"<img src=images/neuzeit-s.png>",
		"<img src=images/news-gothic.png>",
		"<img src=images/nimbus-sans.png>",
		"<img src=images/noe-display.png>",
		"<img src=images/novel-gothic.png>",
		"<img src=images/old-english.png>",
		"<img src=images/omnes.png>",
		"<img src=images/open-sans.png>",
		"<img src=images/optima.png>",
		"<img src=images/p-t-barnum.png>",
		"<img src=images/pistilli-roman.png>",
		"<img src=images/plaak.png>",
		"<img src=images/plantin.png>",
		"<img src=images/playbill.png>",
		"<img src=images/playfair-display.png>",
		"<img src=images/post-antiqua.png>",
		"<img src=images/prestige-12-pitch.png>",
		"<img src=images/pretorian.png>",
		"<img src=images/proxima-nova.png>",
		"<img src=images/px-grotesk.png>",
		"<img src=images/raisonne.png>",
		"<img src=images/reckless.png>",
		"<img src=images/sabon.png>",
		"<img src=images/satyr.png>",
		"<img src=images/savate.png>",
		"<img src=images/schmalfette-grotesk.png>",
		"<img src=images/scriptures-keops-sans.png>",
		"<img src=images/scriptures-memoriam.png>",
		"<img src=images/sentinel-handco.png>",
		"<img src=images/serapion.png>",
		"<img src=images/sharp-grotesk.png>",
		"<img src=images/skia.png>",
		"<img src=images/skolar.png>",
		"<img src=images/sofia.png>",
		"<img src=images/sporting-grotesque.png>",
		"<img src=images/stag-stencil.png>",
		"<img src=images/suisse-int-l.png>",
		"<img src=images/suisse-works.png>",
		"<img src=images/sweet-sans.png>",
		"<img src=images/telefon.png>",
		"<img src=images/tempo.png>",
		"<img src=images/times-new-roman.png>",
		"<img src=images/times.png>",
		"<img src=images/torino.png>",
		"<img src=images/trade-gothic.png>",
		"<img src=images/tuner.png>",
		"<img src=images/tungsten.png>",
		"<img src=images/twentieth-century.png>",
		"<img src=images/typo-upright.png>",
		"<img src=images/ultra-bodoni.png>",
		"<img src=images/ultra-sands.png>",
		"<img src=images/univers-ultra-condensed.png>",
		"<img src=images/univers.png>",
		"<img src=images/venus.png>",
		"<img src=images/verlag.png>",
		"<img src=images/victor.png>",
		"<img src=images/vista-sans.png>",
		"<img src=images/whitney.png>",
		"<img src=images/wigrum.png>",
		"<img src=images/windsor.png>",
		"<img src=images/zenon.png>"
	];

	var randomItem5 = myArray5[Math.floor(Math.random()*myArray5.length)];



	var myArray6 = [
		"<img src=images/abril-text.png>",
		"<img src=images/adelle.png>",
		"<img src=images/adobe-caslon.png>",
		"<img src=images/agipo.png>",
		"<img src=images/aino.png>",
		"<img src=images/akkurat.png>",
		"<img src=images/aktiv-grotesk.png>",
		"<img src=images/akzidenz-grotesk.png>",
		"<img src=images/albertus.png>",
		"<img src=images/alright-sans.png>",
		"<img src=images/alternate-gothic.png>",
		"<img src=images/anderson-grotesk.png>",
		"<img src=images/anostencil.png>",
		"<img src=images/antenna.png>",
		"<img src=images/antique-olive.png>",
		"<img src=images/archer.png>",
		"<img src=images/arial.png>",
		"<img src=images/asul.png>",
		"<img src=images/atlas-grotesk.png>",
		"<img src=images/avenir-next.png>",
		"<img src=images/avenir.png>",
		"<img src=images/balboa.png>",
		"<img src=images/balloon.png>",
		"<img src=images/barracuda-script.png>",
		"<img src=images/baskerville.png>",
		"<img src=images/bello.png>",
		"<img src=images/belwe.png>",
		"<img src=images/benton-sans.png>",
		"<img src=images/big-caslon.png>",
		"<img src=images/big-noodle-titling.png>",
		"<img src=images/block.png>",
		"<img src=images/bodoni.png>",
		"<img src=images/bookman.png>",
		"<img src=images/brandon-grotesque.png>",
		"<img src=images/breite-fette-information.png>",
		"<img src=images/brevier.png>",
		"<img src=images/broadway.png>",
		"<img src=images/brothers.png>",
		"<img src=images/brush-script.png>",
		"<img src=images/brutal-type.png>",
		"<img src=images/bureau-grot.png>",
		"<img src=images/calibre.png>",
		"<img src=images/canela.png>",
		"<img src=images/century-expanded.png>",
		"<img src=images/century-schoolbook.png>",
		"<img src=images/cheltenham.png>",
		"<img src=images/clarendon.png>",
		"<img src=images/coco.png>",
		"<img src=images/cogito.png>",
		"<img src=images/comic-sans.png>",
		"<img src=images/compacta.png>",
		"<img src=images/contact-atf.png>",
		"<img src=images/conto.png>",
		"<img src=images/cooper-black.png>",
		"<img src=images/copperplate-gothic.png>",
		"<img src=images/corvinus.png>",
		"<img src=images/cosimo.png>",
		"<img src=images/curlz.png>",
		"<img src=images/dala-floda.png>",
		"<img src=images/davida.png>",
		"<img src=images/delphin.png>",
		"<img src=images/dic-sans.png>",
		"<img src=images/digestive.png>",
		"<img src=images/documan.png>",
		"<img src=images/dolly.png>",
		"<img src=images/dover-serif-text.png>",
		"<img src=images/druk-text-wide.png>",
		"<img src=images/eckmannpsych.png>",
		"<img src=images/elephant-alias.png>",
		"<img src=images/euclid-flex.png>",
		"<img src=images/eurostile.png>",
		"<img src=images/fakt.png>",
		"<img src=images/favorit.png>",
		"<img src=images/fb-titling-gothic.png>",
		"<img src=images/fedra-sans.png>",
		"<img src=images/ff-din.png>",
		"<img src=images/ff-fago.png>",
		"<img src=images/ff-mark.png>",
		"<img src=images/ff-meta.png>",
		"<img src=images/folio.png>",
		"<img src=images/founders-grotesk.png>",
		"<img src=images/frankfurter.png>",
		"<img src=images/franklin-gothic.png>",
		"<img src=images/freight-sans.png>",
		"<img src=images/frutiger.png>",
		"<img src=images/futura.png>",
		"<img src=images/futura-black.png>",
		"<img src=images/futura-condensed.png>",
		"<img src=images/futura-display.png>",
		"<img src=images/garage-gothic.png>",
		"<img src=images/gemeli-mono.png>",
		"<img src=images/geogrotesque.png>",
		"<img src=images/georgia.png>",
		"<img src=images/gill-kayo.png>",
		"<img src=images/gill-sans.png>",
		"<img src=images/gotham.png>",
		"<img src=images/goudy-old-style.png>",
		"<img src=images/granjon.png>",
		"<img src=images/graphik.png>",
		"<img src=images/gt-america.png>",
		"<img src=images/gt-pressura-mono.png>",
		"<img src=images/gt-sectra.png>",
		"<img src=images/gt-walsheim.png>",
		"<img src=images/hammer.png>",
		"<img src=images/harbour.png>",
		"<img src=images/helvetica-condensed.png>",
		"<img src=images/helvetica.png>",
		"<img src=images/hobo.png>",
		"<img src=images/hollie-script.png>",
		"<img src=images/house-script.png>",
		"<img src=images/house-slant.png>",
		"<img src=images/icone.png>",
		"<img src=images/infini.png>",
		"<img src=images/interstate.png>",
		"<img src=images/italian-black-ornamented.png>",
		"<img src=images/itc-mendoza.png>",
		"<img src=images/itc-souvenir.png>",
		"<img src=images/jaakko.png>",
		"<img src=images/jaf-domus.png>",
		"<img src=images/kabel-black.png>",
		"<img src=images/kabel.png>",
		"<img src=images/karmina-sans.png>",
		"<img src=images/knif-mono.png>",
		"<img src=images/knockout.png>",
		"<img src=images/krul.png>",
		"<img src=images/kurversbrug.png>",
		"<img src=images/kuzanyan.png>",
		"<img src=images/larish-neue.png>",
		"<img src=images/latin-wide.png>",
		"<img src=images/lato.png>",
		"<img src=images/le-griffe.png>",
		"<img src=images/letrista-script.png>",
		"<img src=images/ll-brown.png>",
		"<img src=images/ll-circular.png>",
		"<img src=images/lydian.png>",
		"<img src=images/lyon.png>",
		"<img src=images/maax.png>",
		"<img src=images/maison-neue.png>",
		"<img src=images/marvin.png>",
		"<img src=images/matter.png>",
		"<img src=images/mensch.png>",
		"<img src=images/mercury.png>",
		"<img src=images/miller.png>",
		"<img src=images/minerale.png>",
		"<img src=images/minion.png>",
		"<img src=images/minotaur-sans.png>",
		"<img src=images/minuscule.png>",
		"<img src=images/mistral.png>",
		"<img src=images/monotype-grotesque.png>",
		"<img src=images/morion.png>",
		"<img src=images/mrs-eaves.png>",
		"<img src=images/museo-sans.png>",
		"<img src=images/neue-haas-grotesk.png>",
		"<img src=images/neue-helvetica.png>",
		"<img src=images/neutraface.png>",
		"<img src=images/neuzeit-s.png>",
		"<img src=images/news-gothic.png>",
		"<img src=images/nimbus-sans.png>",
		"<img src=images/noe-display.png>",
		"<img src=images/novel-gothic.png>",
		"<img src=images/old-english.png>",
		"<img src=images/omnes.png>",
		"<img src=images/open-sans.png>",
		"<img src=images/optima.png>",
		"<img src=images/p-t-barnum.png>",
		"<img src=images/pistilli-roman.png>",
		"<img src=images/plaak.png>",
		"<img src=images/plantin.png>",
		"<img src=images/playbill.png>",
		"<img src=images/playfair-display.png>",
		"<img src=images/post-antiqua.png>",
		"<img src=images/prestige-12-pitch.png>",
		"<img src=images/pretorian.png>",
		"<img src=images/proxima-nova.png>",
		"<img src=images/px-grotesk.png>",
		"<img src=images/raisonne.png>",
		"<img src=images/reckless.png>",
		"<img src=images/sabon.png>",
		"<img src=images/satyr.png>",
		"<img src=images/savate.png>",
		"<img src=images/schmalfette-grotesk.png>",
		"<img src=images/scriptures-keops-sans.png>",
		"<img src=images/scriptures-memoriam.png>",
		"<img src=images/sentinel-handco.png>",
		"<img src=images/serapion.png>",
		"<img src=images/sharp-grotesk.png>",
		"<img src=images/skia.png>",
		"<img src=images/skolar.png>",
		"<img src=images/sofia.png>",
		"<img src=images/sporting-grotesque.png>",
		"<img src=images/stag-stencil.png>",
		"<img src=images/suisse-int-l.png>",
		"<img src=images/suisse-works.png>",
		"<img src=images/sweet-sans.png>",
		"<img src=images/telefon.png>",
		"<img src=images/tempo.png>",
		"<img src=images/times-new-roman.png>",
		"<img src=images/times.png>",
		"<img src=images/torino.png>",
		"<img src=images/trade-gothic.png>",
		"<img src=images/tuner.png>",
		"<img src=images/tungsten.png>",
		"<img src=images/twentieth-century.png>",
		"<img src=images/typo-upright.png>",
		"<img src=images/ultra-bodoni.png>",
		"<img src=images/ultra-sands.png>",
		"<img src=images/univers-ultra-condensed.png>",
		"<img src=images/univers.png>",
		"<img src=images/venus.png>",
		"<img src=images/verlag.png>",
		"<img src=images/victor.png>",
		"<img src=images/vista-sans.png>",
		"<img src=images/whitney.png>",
		"<img src=images/wigrum.png>",
		"<img src=images/windsor.png>",
		"<img src=images/zenon.png>"
	];

	var randomItem6 = myArray6[Math.floor(Math.random()*myArray6.length)];



	$("#t-one").html(randomItem);
	$("#t-two").html(randomItem2);
	$("#t-three").html(randomItem3);
	$("#t-four").html(randomItem4);
	$("#first-font").html(randomItem5);
	$("#second-font").html(randomItem6);

});